name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    # Install gettext package
    - name: Install gettext
      run: sudo apt-get install -y gettext autopoint

    # Patching onto minidjvu-mod according to provided steps
    - name: Setup minidjvu-mod with djvudict
      run: |
        cd /tmp
        git clone https://github.com/rmast/minidjvu-mod.git
        git clone https://github.com/rmast/djvudict.git
        cd ./minidjvu-mod
        cp ../djvudict/tools/* ./tools/
        git apply ../djvudict/changes.diff
        autoreconf --install
        ./configure
        make

#    - name: Upload Artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: djvudict
#        path: /tmp/minidjvu-mod  # Adjust the path to match your actual artifacts
